apiVersion: v2
name: grafana-operator
description: Grafana Operator
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: grafana-operator
    version: 5.22.1
    repository: oci://ghcr.io/grafana/helm-charts
