apiVersion: v2
name: garage
description: Operator-managed Garage cluster (GarageCluster CR) plus its S3 API HTTPRoute
type: application
version: 1.0.0
home: https://garagehq.deuxfleurs.fr/
icon: https://garagehq.deuxfleurs.fr/images/garage-logo.svg

keywords:
- geo-distributed
- read-after-write-consistency
- s3-compatible

sources:
- https://git.deuxfleurs.fr/Deuxfleurs/garage.git

maintainers: []
