apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .Values.kafka.traceTopic.name }}
  labels:
    # Selects the entityOperator.topicOperator of the "platform" Kafka CR
    # (kafka.yaml) as this topic's reconciler.
    strimzi.io/cluster: platform
spec:
  partitions: {{ .Values.kafka.traceTopic.partitions }}
  replicas: {{ .Values.kafka.replicationFactor }}
  config:
    min.insync.replicas: {{ .Values.kafka.minInsyncReplicas }}
