# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
{{- if .Values.bgp.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bgp-auth-secret
  namespace: kube-system
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1h0m0s"
  dataFrom:
    - extract:
        key: idp/platform/networking/bgp-auth-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
