# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  source:
    repoURL: {{ include "platform-apps.repoURL" . }}
    targetRevision: {{ include "platform-apps.targetRevision" . }}
    path: charts/argocd-config
    helm:
      releaseName: argocd-config
      valueFiles:
        - values.yaml
        - environments/{{ .Values.environment }}.yaml
      parameters:
        - name: environment
          value: {{ .Values.environment | quote }}
        - name: backstage.repoURL
          value: {{ include "backstage.repoURL" . | quote }}
        - name: crossplaneCompositions.repoURL
          value: {{ include "crossplane-compositions.repoURL" . | quote }}
        - name: userApps.repoURL
          value: {{ include "user-apps.repoURL" . | quote }}

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
