# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
# See https://kyverno.io/docs/installation/platform-notes/#notes-for-argocd-users for best practices
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ include "platform-apps.repoURL" . }}
    targetRevision: {{ include "platform-apps.targetRevision" . }}
    path: charts/kyverno
    helm:
      releaseName: kyverno
      values: |
        webhookLabels:
          app.kubernetes.io/managed-by: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
