# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
{{- if .Values.longhorn.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - pre-delete-finalizer.argocd.argoproj.io
    - pre-delete-finalizer.argocd.argoproj.io/cleanup
spec:
  project: default

  source:
    repoURL: {{ include "platform-apps.repoURL" . }}
    targetRevision: {{ include "platform-apps.targetRevision" . }}
    path: charts/longhorn
    helm:
      releaseName: longhorn
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
