apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.path }}
      version: {{ .Values.vault.version }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.auth.kubernetes.mountPath }}
          role: {{ .Values.vault.auth.kubernetes.role }}
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets-operator"
            {{- with .Values.vault.auth.kubernetes.audiences }}
            audiences:
              {{- toYaml . | nindent 14 }}
            {{- end }}
