apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-database-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1h0m0s"
  dataFrom:
  - extract:
      key: idp/platform/observability/grafana-database
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
