# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: "{{ .Values.clusterIssuer.acmeEmail }}"
    server: "{{ .Values.clusterIssuer.acmeServer }}"
    privateKeySecretRef:
      name: letsencrypt-cloudflare
    solvers:
      - dns01:
          cloudflare: # TODO Make configurable, rottlr.de is managed by Cloudflare and rottler.io by AWS R53
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
