gateway:
  hostnames:
    prometheus: prometheus.dev.idp.rottlr.de
    alertmanager: alertmanager.dev.idp.rottlr.de

kube-prometheus-stack:
  # NOTE: Prometheus does not support horizontal scaling. Either enable Thanos or directly switch to Mimir for EKS clusters.
  prometheus:
    replicas: 1

  alertmanager:
    alertmanagerSpec:
      replicas: 2
