{
 "title": "Alertmanager / Overview",
 "tags": [ "alertmanager-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(alertmanager_alerts, cluster)"
   },
   {
    "name": "integration",
    "query": "label_values(alertmanager_notifications_total{integration=~\".*\"}, integration)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "timeseries",
   "description": "current set of alerts stored in the Alertmanager",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{cluster=~\"$cluster\"}) by (cluster,instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alerts receive rate",
   "type": "timeseries",
   "description": "rate of successful and invalid alerts received by the Alertmanager",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(alertmanager_alerts_received_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,instance)",
     "legendFormat": "{{instance}} Received"
    },
    {
     "expr": "sum(rate(alertmanager_alerts_invalid_total{cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,instance)",
     "legendFormat": "{{instance}} Invalid"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$integration: Notifications Send Rate",
   "type": "timeseries",
   "description": "rate of successful and invalid notifications sent by the Alertmanager",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "repeat": "integration",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(alertmanager_notifications_total{cluster=~\"$cluster\", integration=\"$integration\"}[$__rate_interval])) by (integration,cluster,instance)",
     "legendFormat": "{{instance}} Total"
    },
    {
     "expr": "sum(rate(alertmanager_notifications_failed_total{cluster=~\"$cluster\", integration=\"$integration\"}[$__rate_interval])) by (integration,cluster,instance)",
     "legendFormat": "{{instance}} Failed"
    }
   ]
  },
  {
   "title": "$integration: Notification Duration",
   "type": "timeseries",
   "description": "latency of notifications sent by the Alertmanager",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "repeat": "integration",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum(rate(alertmanager_notification_latency_seconds_bucket{cluster=~\"$cluster\", integration=\"$integration\"}[$__rate_interval])) by (le,cluster,instance)\n)\n",
     "legendFormat": "{{instance}} 99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50,\n  sum(rate(alertmanager_notification_latency_seconds_bucket{cluster=~\"$cluster\", integration=\"$integration\"}[$__rate_interval])) by (le,cluster,instance)\n)\n",
     "legendFormat": "{{instance}} Median"
    },
    {
     "expr": "sum(rate(alertmanager_notification_latency_seconds_sum{cluster=~\"$cluster\", integration=\"$integration\"}[$__rate_interval])) by (cluster,instance)\n/\nsum(rate(alertmanager_notification_latency_seconds_count{cluster=~\"$cluster\", integration=\"$integration\"}[$__rate_interval])) by (cluster,instance)\n",
     "legendFormat": "{{instance}} Average"
    }
   ]
  }
 ]
}