# https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/
loki:
  lokiCanary:
    priorityClassName: monitoring-daemonset

  loki:
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true

  minio:
    enabled: false
