# Cilium BGP Configuration
bgp:
  enabled: false
  clusterConfiguration:
    environment:
    name:
    zone:
  localASN:
  peerASN:
  peerAddress:

# Cilium LoadBalancer Configuration
lbPool:
  enabled: false
  startIP:
  stopIP:

gatewayExternalIP:
