apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3" # Required grafana-database
spec:
  project: default

  source:
    repoURL: https://gitlab.home.rottlr.de/idp/platform/idp-argocd-platform-apps.git
    targetRevision: main
    path: charts/grafana
    helm:
      releaseName: grafana

  destination:
    server: https://kubernetes.default.svc
    namespace: grafana

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
