apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-database
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # requires cloudnative-pg
spec:
  project: default

  source:
    repoURL: https://gitlab.home.rottlr.de/idp/platform/argocd-platform.git
    targetRevision: main
    path: charts/grafana-database
    helm:
      releaseName: grafana-database

  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-database

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
