apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://gitlab.home.rottlr.de/idp/platform/argocd-platform.git
    targetRevision: main
    path: charts/k8s-monitoring
    helm:
      releaseName: k8s-monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
