apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://gitlab.home.rottlr.de/idp/platform/argocd-platform.git
    targetRevision: main
    path: charts/kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
