apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://gitlab.home.rottlr.de/idp/platform/idp-argocd-platform-apps.git
    targetRevision: main
    path: charts/loki
    helm:
      releaseName: loki

  destination:
    server: https://kubernetes.default.svc
    namespace: loki

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
