# Values for kyverno subchart
# See https://kyverno.io/docs/installation/platform-notes/#notes-for-argocd-users for best practices
kyverno:
  admissionController:
    replicas: 1
    resources:
      requests:
        memory: 128Mi

  backgroundController:
    replicas: 1
    resources:
      requests:
        memory: 128Mi

  cleanupController:
    replicas: 1
    resources:
      requests:
        memory: 128Mi

  reportsController:
    replicas: 1
    resources:
      requests:
        memory: 128Mi

  config:
    preserve: false
