# Vault configuration
cert-manager:
  installCRDs: true
  prometheus:
    enabled: true
    podmonitor:
      enabled: true
  # Resource optimization based on KRR recommendations
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 128Mi
  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 128Mi
  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 128Mi

clusterIssuer:
  acmeEmail: benjamin@rottler.io
  acmeServer: https://acme-v02.api.letsencrypt.org/directory
certificate:
  externalDomain: k8s.home.rottlr.de # Overwrite in ./environments/<env>.yaml
  includeWildcardCertificate: true
