keda:
  crds:
    install: true

  resources:
    operator:
      requests:
        memory: 64Mi
      limits:
        memory: 512Mi
    metricServer:
      requests:
        memory: 64Mi
      limits:
        memory: 512Mi
    webhooks:
      requests:
        memory: 32Mi
      limits:
        memory: 128Mi
