# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
# https://argo-cd.readthedocs.io/en/latest/operator-manual/webhook/#alternative
{{ if eq .Values.environment "homelab" -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-webhook-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1h0m0s"
  target:
    name: argocd-gitlab-webhook-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: webhook.gitlab.secret
      remoteRef:
        key: idp/platform/argocd/webhook-gitlab-secret
        property: webhook.gitlab.secret
{{- end -}}
