# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-database-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1h0m0s"
  data:
  - secretKey: username
    remoteRef:
      key: idp/platform/backstage/postgresql
      property: POSTGRES_USER
  - secretKey: password
    remoteRef:
      key: idp/platform/backstage/postgresql
      property: POSTGRES_PASSWORD
