vault:
  server: "https://vault.dev.idp.rottlr.de"
  auth:
    kubernetes:
      audiences:
        - "vault"
    createResources: false

external-secrets:
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
  webhook:
    replicaCount: 2
    podDisruptionBudget:
      enabled: true
  certController:
    replicaCount: 2
    podDisruptionBudget:
      enabled: true
